version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: perfect10k_postgres
    environment:
      POSTGRES_DB: perfect10k
      POSTGRES_USER: perfect10k
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U perfect10k"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Redis Cache (optional, for future use)
  redis:
    image: redis:7-alpine
    container_name: perfect10k_redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Perfect10k API
  api:
    build:
      context: .
      dockerfile: Dockerfile.simple
    container_name: perfect10k_api
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://perfect10k:password@postgres:5432/perfect10k
      - SECRET_KEY=your-super-secret-key-change-in-production
      - DEBUG=true
      - ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    volumes:
      - .:/app
    depends_on:
      postgres:
        condition: service_healthy
    command: python run.py
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
  redis_data: